name: Polymathy Collective
favicon: null
layout_spectrum: 0.84489
typography_spectrum: 0.58473
title: The Polymathy Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#585550'
    - '#78756a'
    - '#d3cfb8'
    - '#f3efdb'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
